# Generated by Django 4.1.5 on 2024-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=1900),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='number',
            field=models.IntegerField(default=1900),
        ),
    ]
